# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 173f8a361375c2edb18328606e621e04b91d19ec757e8de64c6cffae01e84664048071b0086f993eaac5cf37cd0b2cf1f9dd012e0124f6f58d3faf7a514c0d18

test:
  secret_key_base: 31c4e3cd072a7e20b407a1511b45c9c6037da2d588a23e8fdbe7cca528eb5cb8d2ce040fc6408ea4bb3713e663e6fa25434f1984deb008e077d1f19d17f83c6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
